#!/usr/bin/env bash
#confihure server with redire

sudo apt-get -y update
sudo apt-get -y install nginx
file=/etc/nginx/sites-available/default
sudo service nginx start

msg="location /redirect_me {\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}\n"
sudo sed -i "24i $msg" $file
sudo service nginx restart
