#!/usr/bin/env bash
#confihure server with redire

sudo apt-get -y update
sudo apt-get -y install nginx
file=/etc/nginx/sites-available/default
sudo service nginx start

msg="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$msg/" $file

echo "https://www.youtube.com/watch?v=QH2-TGUlwu4" > /var/www/html/redirect_me
sudo service nginx restart 
