#!/usr/bin/env bash
# 404vnot found

#update packages before installatio
sudo apt-get update
sudo apt-get install -y nginx

#create file
echo "Hello World!" > /var/www/html/index.html

#moved permananttly
msg="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$msg/" /etc/nginx/sites-enabled/default;

echo "https://www.youtube.com/watch?v=QH2-TGUlwu4" > /var/www/html/redirect_me

#404 not found
echo "Ceci n'est pas une page" > /var/www/html/404.html

new_str="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_str/" /etc/nginx/sites-enabled/default;

#testing server errors
sudo nginx -t

#restartin the server
sudo service nginx restart
