#!/usr/bin/bash
# Install HAProxy load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy

# Enable HAProxy to start on boot
file="/etc/default/haproxy"
sudo sed -i "#20i ENABLED=1" $file

# Backup the original HAProxy configuration file
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.save

# Create a new HAProxy configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
frontend myserver
    bind *:80
    mode http
    default_backend my_servers

backend my_servers
    balance roundrobin
    mode http
    server server1 52.4.151.229 check
    server server2 107.23.109.36 check
EOL

# Restart the HAProxy service to apply the new configuration
sudo service haproxy restart

