#!/usr/bin/python3
import csv
import requests
from sys import argv

def export_csv(id):
    usr = requests.get(f"https://jsonplaceholder.typicode.com/users/{id}").json().get("username")
    data = requests.get(f"https://jsonplaceholder.typicode.com/users/{id}/todos").json()

    li = []
    for i in data:
        listng = [f"{id}", f"{usr}", f"{i.get("completed")}", f"{i.get("title")}"]
        li.append(listng)
    
    with open(f"{id}.csv", "w") as csvfile:
        writer = csv.writer(csvfile)
        writer.writerows(li)

if __name__ == "__main__":
    export_csv(argv[1])